api/urls.py
from django.urls import path

from .views import (
    ProjectListAPIView,
    ProjectDetailAPIView,
    AboutMeAPIView,
    ContactMeAPIView,
    EducationListAPIView,
    ProductDocAPIView,
    ProductListAPIView,
    ProductDetailAPIView,
    EventListAPIView, EventDetailAPIView, JobCreateAPIView,
)

urlpatterns = [
    path("about/", AboutMeAPIView.as_view(), name="about-me"),
    path("contact/", ContactMeAPIView.as_view(), name="contact-me"),
    path("product-doc/", ProductDocAPIView.as_view(), name="product-doc"),
    path('products/', ProductListAPIView().as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailAPIView.as_view(), name='product-detail'),
    path("educations/", EducationListAPIView.as_view(), name="education-list"),
    path('projects/', ProjectListAPIView.as_view(), name='project-list'),
    path('projects/<int:pk>/', ProjectDetailAPIView.as_view(), name='project-detail'),

    path('events/', EventListAPIView.as_view(), name='event-list'),
    path('events/<int:pk>/', EventDetailAPIView.as_view(), name='event-detail'),

    path('jobs/create/', JobCreateAPIView.as_view(), name='job-create'),
    path('design/create/', JobCreateAPIView.as_view(), name='designorder-create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('portfolio.urls')),
    path("partoadmin/", admin.site.urls),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("", landing, name='landing'),
    path("toggle/", toggle_page, name='toggle'),
    path("description/", description, name='description'),
    path("event/list/", event_list_view, name='event-list'),
    path("event/<int:pk>/", event_detail_view, name='event-detail'),
    path("contacts/", contact, name='contacts'),
    path("jobs/", job, name='jobs'),

    path("project/list/", project_list_view, name='project-list'),
    path("project/<int:pk>/", project_detail_view, name='project-detail'),
    path("product/", get_product_view, name='product-retrieve'),
    path("design/create/", create_design_view, name='design-create'),
    path("education/", education_view, name='education'),
]

portfolio/models.py
# myapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class SingletonModel(models.Model):
    """Abstract base class for singleton models"""

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        # Delete all other instances if they exist
        self.__class__.objects.exclude(id=self.id).delete()
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        """Get or create the single instance"""
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls.objects.create()


class AboutMe(SingletonModel):
    caption = models.TextField()
    photo = models.ImageField(upload_to='about/')
    document = models.FileField(upload_to='products/', null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "About Me"  # Nice admin name

    def __str__(self):
        return self.title


class ContactMe(SingletonModel):
    mobile = models.CharField(max_length=15)
    phone = models.CharField(max_length=15)
    email1 = models.EmailField(blank=True, null=True)
    email2 = models.EmailField(blank=True, null=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Contact Me"  # Nice admin name

    def __str__(self):
        return f'{self.mobile}, {self.phone}, {self.email1}, {self.email2}'


class DesignOrder(models.Model):
    class ContactMethod(models.TextChoices):
        TELEGRAM = 'TL', _('telegram')
        WHATSAPP = 'WP', _('whatsapp')
        EMAIL = 'EL', _('email')

    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=255)
    contact_method = models.CharField(max_length=3, choices=ContactMethod.choices, default=ContactMethod.TELEGRAM)

    uploaded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Education(models.Model):
    tilte = models.CharField(max_length=200)
    caption = models.TextField(null=True, blank=True, default="No caption provided")
    url = models.URLField(null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProductDoc(SingletonModel):
    application = models.FileField(upload_to='products/', null=True, blank=True)
    presentation = models.FileField(upload_to='products/', null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product docs"  # Nice admin name

    def __str__(self):
        app_name = self.application.name.split('/')[-1] if self.application else "No application"
        pres_name = self.presentation.name.split('/')[-1] if self.presentation else "No presentation"
        return f"Application: {app_name}, Presentation: {pres_name}"


class Product(models.Model):
    image = models.ImageField(upload_to='products/')
    caption = models.TextField(null=True, blank=True, default="No caption provided")

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Products"
        ordering = ['created_at']

    def __str__(self):
        img_name = self.image.name.split('/')[-1] if self.image else "No image"
        caption_preview = (self.caption[:15] + '...') if self.caption and len(self.caption) > 15 else (
                self.caption or "No caption")
        return f"Image: {img_name}, Caption: {caption_preview}"


class Project(models.Model):
    class Status(models.TextChoices):
        PLANNED = 'PL', _('Planned')
        IN_PROGRESS = 'IP', _('In Progress')
        COMPLETED = 'CO', _('Completed')
        ON_HOLD = 'OH', _('On Hold')
        CANCELLED = 'CL', _('Cancelled')

    name = models.CharField(max_length=255)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.PLANNED
    )
    usage = models.CharField(max_length=255)
    project_date = models.DateField()

    # thumbnail = models.OneToOneField(
    #     'ProjectImage',
    #     on_delete=models.SET_NULL,
    #     null=True,
    #     blank=True,
    #     related_name='main_thumbnail'
    # )
    thumbnail = models.ImageField(upload_to='projects/thumbnails/', null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ProjectImage(models.Model):
    project = models.ForeignKey(
        Project,
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='projects/')
    caption = models.TextField(null=True, blank=True, default="No caption provided")

    uploaded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # return f"{self.project.name} - {self.caption or self.image.name}"
        return f"{self.caption or self.image.name}"


class Event(models.Model):
    class Status(models.TextChoices):
        PLANNED = 'PL', _('Planned')
        IN_PROGRESS = 'IP', _('In Progress')
        COMPLETED = 'CO', _('Completed')
        ON_HOLD = 'OH', _('On Hold')
        CANCELLED = 'CL', _('Cancelled')

    name = models.CharField(max_length=255)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.PLANNED
    )
    usage = models.CharField(max_length=255)
    event_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    thumbnail = models.ImageField(upload_to='events/thumbnails/', null=True, blank=True)

    def __str__(self):
        return self.name


class EventImage(models.Model):
    event = models.ForeignKey(
        Event,
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='events/')
    caption = models.TextField(null=True, blank=True, default="No caption provided")

    uploaded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # return f"{self.event.name} - {self.caption or self.image.name}"
        return f"{self.caption or self.image.name}"


class Job(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone_number = models.CharField(max_length=255)

    uploaded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)

portfolio/views.py
import time

# Create your views here.
from django.shortcuts import render, get_object_or_404

from .models import AboutMe, Product, Project, Event, ContactMe


def landing(request):
    # Get the first (and only) AboutMe entry
    about = AboutMe.objects.first()
    projects = Project.objects.all().order_by('-created_at')

    context = {'office': True, 'active_section': 'projects', 'projects': projects, 'object': about, }
    request.session['current_content'] = 'office'

    return render(request, 'portfolio/landing.html', context=context)


def toggle_page(request):
    current = request.session.get('current_content', 'office')
    if current == 'office':
        request.session['current_content'] = 'parto'
        # Get the first (and only) AboutMe entry
        about = AboutMe.objects.first()
        context = {'active_section': 'description', 'object': about, }
        return render(request, 'portfolio/partials/parto/index.html', context=context)
    elif current == 'parto':
        request.session['current_content'] = 'office'
        # # Get the first (and only) AboutMe entry
        # about = AboutMe.objects.first()
        projects = Project.objects.all().order_by('-created_at')

        context = {'active_section': 'projects', 'projects': projects}
        return render(request, 'portfolio/partials/office/index.html', context=context)


def description(request):
    # Get the first (and only) AboutMe entry
    about = AboutMe.objects.first()
    context = {'active_section': 'description', 'object': about, }
    return render(request, 'portfolio/partials/parto/description.html', context)


def event(request):
    context = {'active_section': 'events', }
    return render(request, 'portfolio/partials/parto/events.html', context)


def event_list_view(request):
    events = Event.objects.all().order_by('-created_at')
    context = {'active_section': 'events', 'events': events}
    return render(request, 'portfolio/partials/parto/events.html', context)


def event_detail_view(request, pk):
    event = get_object_or_404(Event, pk=pk)
    context = {'event': event, 'images': event.images.all()}
    return render(request, 'portfolio/partials/parto/event-detail.html', context)


def contact(request):
    contact_me = ContactMe.objects.first()
    context = {'active_section': 'contacts', 'object':contact_me}
    return render(request, 'portfolio/partials/parto/contacts.html', context)


def job(request):
    context = {'active_section': 'jobs', }
    return render(request, 'portfolio/partials/parto/jobs.html', context)


def project_list_view(request):
    projects = Project.objects.all().order_by('-created_at')
    context = {'active_section': 'projects', 'projects': projects}
    return render(request, 'portfolio/partials/office/projects.html', context)


def project_detail_view(request, pk):
    project = get_object_or_404(Project, pk=pk)
    context = {'project': project, 'images': project.images.all()}
    return render(request, 'portfolio/partials/office/project.html', context)


def get_product_view(request):
    product = Product.objects.first()
    # time.sleep(3)
    context = {'active_section': 'production', 'product': product, }
    return render(request, 'portfolio/partials/office/production.html', context)


def create_design_view(request):
    context = {'active_section': 'design_form', }
    return render(request, 'portfolio/partials/office/design-form.html', context)


def education_view(request):
    context = {'active_section': 'education', }
    return render(request, 'portfolio/partials/office/education.html', context)

portfolio/templates/portfolio/partials/office-old/design-form.html
{% load static %}
<section>
    <div class="row m-3 justify-content-center">
        <div class="col-xxl-4">
            <div>
                <div>
                    <h5>Hello, welcome to Design Order section...
                    </h5>
                </div>
                <div>
                    <form id="regForm" class="mt-4" method="post">
                        {% csrf_token %}

                        <!-- One "tab" for each step in the form: -->
                        <div class="tab">
                                <label class=" my-1" for="id_name">full name</label>

                                <p><input class="x-input" placeholder="Your Full Name..."
                                          oninput="this.className = 'x-input'">
                                </p>
                            <div class="dropdown">
                                <label class=" my-1" for="id_contact_method">Preferred Method of Contact</label>
                                <select class="form-select x-btn-primary" name="contact_method" id="id_contact_method">
                                    <option value="" selected>Does not matter</option>
                                    <option value="Email (and Google meet)">Email (and Google meet)</option>
                                    <option value="WhatsApp">WhatsApp</option>
                                    <option value="Telegram">Telegram</option>
                                    <option value="Skype">Skype</option>
                                </select>
                            </div>
{#                            <div class="radio-container-1 d-flex flex-column mt-3">#}
{#                                <h6>How can I help you?</h6>#}
{#                                <input type="radio" class="btn-check" name="options" id="option1" autocomplete="off"#}
{#                                       oninput="this.className = 'btn-check'">#}
{#                                <label class="x-btn-primary my-1" for="option1">Radio</label>#}
{#                                <input type="radio" class="btn-check" name="options" id="option2" autocomplete="off"#}
{#                                       oninput="this.className = 'btn-check'">#}
{#                                <label class="x-btn-primary my-1" for="option2">Radio</label>#}
{#                                <input type="radio" class="btn-check" name="options" id="option3" autocomplete="off"#}
{#                                       oninput="this.className = 'btn-check'">#}
{#                                <label class="x-btn-primary my-1" for="option3">Radio</label>#}
{#                                <input type="radio" class="btn-check" name="options" id="option4" autocomplete="off"#}
{#                                       oninput="this.className = 'btn-check'">#}
{#                                <label class="x-btn-primary my-1" for="option4">Radio</label>#}
{#                            </div>#}

                        </div>
                        <div class="tab">
                            <h6>What is your state?</h6>
                            <p><input class="x-input" placeholder="Your State..." oninput="this.className = 'x-input'">
                            </p>
                        </div>

                        <div class="tab">
                            <h6>Enter your phone number</h6>
                            <p>this number will just use for business purpose</p>

                            <p><input class="x-input" placeholder="Your Phone Number..."
                                      oninput="this.className = 'x-input'">
                            </p>

                        </div>

                        <div class="tab">
                            <div class="radio-container-2 d-flex flex-column mt-3">
                                <h6>Full Name</h6>
                                <p><input class="x-input" placeholder="Your Full Name..."
                                          oninput="this.className = 'x-input'">
                                </p>
                                <input type="radio" class="btn-check" name="options" id="female" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="female">female</label>
                                <input type="radio" class="btn-check" name="options" id="male" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="male">male</label>
                            </div>
                        </div>
                        <div class="tab">
                            <h6>Your Project Area in metric system</h6>
                            <p><input class="x-input" placeholder="Area..." oninput="this.className = 'x-input'">
                            </p>
                        </div>
                        <div class="tab">
                            <div class="radio-container-6 d-flex flex-column mt-3">
                                <h6>project situation</h6>
                                <input type="radio" class="btn-check" name="options" id="6-1" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="6-1">opt</label>
                                <input type="radio" class="btn-check" name="options" id="6-2" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="6-2">opt</label>
                                <input type="radio" class="btn-check" name="options" id="6-3" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="6-3">opt</label>
                            </div>
                        </div>
                        <div class="tab">
                            <div class="radio-container-7 d-flex flex-column mt-3">
                                <h6>Project start time</h6>
                                <input type="radio" class="btn-check" name="options" id="7-1" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="7-1">opt</label>
                                <input type="radio" class="btn-check" name="options" id="7-2" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="7-2">opt</label>
                                <input type="radio" class="btn-check" name="options" id="7-3" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="7-3">opt</label>
                            </div>
                        </div>
                        <div class="tab">
                            <h6>City or Section</h6>
                            <p><input class="x-input" placeholder="Your City..." oninput="this.className = 'x-input'">
                            </p>
                        </div>
                        <div class="tab">
                            <div class="radio-container-9 d-flex flex-column mt-3">
                                <h6>How do you find me?</h6>
                                <input type="radio" class="btn-check" name="options" id="9-1" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="9-1">opt</label>
                                <input type="radio" class="btn-check" name="options" id="9-2" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="9-2">opt</label>
                                <input type="radio" class="btn-check" name="options" id="9-3" autocomplete="off"
                                       oninput="this.className = 'btn-check'">
                                <label class="x-btn-primary my-1" for="9-3">opt</label>
                            </div>
                        </div>
                        <div class="tab">
                            <h6>Your Project photos</h6>
                            <p><input class="x-input" placeholder="Project Photos..."
                                      oninput="this.className = 'x-input'">
                            </p>
                        </div>
                        <div class="mt-3" style="overflow:auto;">
                            <div style="float:right;">
                                <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
                                <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
                            </div>
                        </div>

                        <!-- Circles which indicates the steps of the form: -->
                        <div style="text-align:center;margin-top:40px;">
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                            <span class="step"></span>
                        </div>

                    </form>
                </div>
            </div>
        </div>
        {#        <div class="col-4">#}
        {##}
        {#            <img src="{{ MEDIA_URL }}aboutme/billie.jpg" alt="my photo" class="w-100">#}
        {#        </div>#}
    </div>
</section>
{#<script src="{% static 'js/multiple-step-form.js' %}"></script>#}

portfolio/templates/portfolio/partials/office-old/education.html
{% load static %}
<section>
    <div class="row m-3">
        <div class="col-12">

            <p>

this is education page from youtube
            </p>
        </div>
{#        <div class="col-4">#}
{##}
{#            <img src="{{ MEDIA_URL }}aboutme/billie.jpg" alt="my photo" class="w-100">#}
{#        </div>#}
    </div>
</section>

portfolio/templates/portfolio/partials/office-old/index.html
<div class="col-xxl-11 col-xl-10 col-lg-10 col-md-9 col-sm-12 col-12">
    <div class="loading-indicator">
        Loading...
    </div>

    <div class="main-content">

        {% include 'portfolio/partials/office/projects.html' %}

    </div>

</div>
<div class="desktop-menu col-xxl-1 col-xl-2 col-lg-2 col-md-3 x-bg-primary">
    <!-- Fixed Sidebar for Desktop -->
    <div class="sidebar mt-5">
        <nav>
            <ul class="nav nav-bar flex-column">
                <li class="nav-item">
                    <a class="link-light nav-link x-active disabled"
                       id="projects"
                       href=""
                       hx-get="{% url 'project-list' %}"
                       hx-target=".main-content"
                       hx-indicator=".loading-indicator"
                       hx-on:click="setActive(this)">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="link-light nav-link"
                       id="production"
                       href=""
                       hx-get="{% url 'product-retrieve' %}"
                       hx-target=".main-content"
                       hx-indicator=".loading-indicator"
                       hx-on:click="setActive(this)">Production</a>
                </li>
                <li class="nav-item">
                    <a class="link-light nav-link"
                       id="design-order"
                       href=""
                       hx-get="{% url 'design-create' %}"
                       hx-target=".main-content"
                       hx-indicator=".loading-indicator"
                       hx-on:click="setActive(this)">Design order</a>
                </li>
                <li class="nav-item">
                    <a class="link-light nav-link"
                       id="education"
                       href=""
                       hx-get="{% url 'education' %}"
                       hx-target=".main-content"
                       hx-on:click="setActive(this)">Education</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

portfolio/templates/portfolio/partials/office-old/production.html
{% load static %}
<!-- HTML -->
<section class="container-fluid">
    <div class="row m-3">
        <div class="col-12 col-md-8 p-3">
            <p class="lead">{{ product.description }}</p>
        </div>
        <div class="col-12 col-md-4">
            <div class="slider-container position-relative overflow-hidden" >
                <div class="slider d-flex">
                    {% for image in product.images.all %}
                        <div class="slide w-100 flex-shrink-0 text-center">
                            <img src="{{ image.image.url }}"
                                 alt="{{ image.alt_text|default:'Product image' }}"
                                 class="img-fluid ">
                        </div>
                    {% endfor %}
                </div>

                <div class="slider-nav position-absolute top-50 start-0 end-0 d-flex justify-content-between px-3 translate-middle-y">
                    <button data-slider-action="prev"
                            class="xxx-slide slider-button btn btn-dark">
                        ‹
                    </button>
                    <button data-slider-action="next"
                            class="xxx-slide slider-button btn btn-dark">
                        ›
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/slider.js' %}"></script>

portfolio/templates/portfolio/partials/office-old/projects.html
{% load static %}
<!--
<section class="project-section">
    <div class="row m-3 gx-2">

{#         Repeat the following col for 40 tiles #}
        {#        <div class="col-xxl-2">#}
        {#            <div class="card">#}
        {#                <img src="{{ MEDIA_URL }}aboutme/billie.jpg" alt="my photo" class="w-100">#}
        {#            </div>#}
        {#        </div>#}
{#        {% for project in projects %}#}

            <div class="col-6 col-sm-4 col-md-3 col-lg-2 col-xl-2 col-xxl-1 mb-2">
                <a
                        class="nav-link"
                        href=""
{#                        hx-get="{% url 'project-detail' project.pk %}"#}
                        hx-target=".project-section">
                    <div class="card border-0">
                        <div class="square-container position-relative overflow-hidden">
{#                            <img src="{{ project.thumbnail.image.url }}"#}
                                 alt="the project preview"
                                 class="position-absolute w-100 h-100"
                                 style="object-fit: cover; object-position: center center;">
                        </div>

                        <div class="card-overlay hover-shadow text-light">
                            <div class="p-1">
{#                                <h6>{{ project.name }}</h6>#}
{#                                <p style="font-size: 10pt;">{{ project.get_status_display }}</p>#}
{#                                <p style="font-size: 10pt;">{{ project.project_date.year }}</p>#}

                            </div>
                        </div>
                    </div>
                </a>
            </div>
{#        {% endfor %}#}
    </div>
</section>
-->

<template id="projects-section">
    <span id="page-title"><h2>Projects</h2></span>
    <div id="projects-container">
        <div id="page-header" class="projects-header"></div>
        <div id="projects-content">
            <div class="cell">cell</div>
            <div class="cell">cell</div>
            <div class="cell">cell</div>
            <div class="cell">cell</div>
            <div class="cell">cell</div>
            <div class="cell">cell</div>
            <div id="page-number">1 2 3</div>

        </div>
    </div>
</template>